apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: blagateway
  namespace: blagenda
spec:
  gatewayClassName: gke-l7-global-external
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "blagenda.diamondy.dev"
