apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: blagroute
  namespace: blagenda
spec:
  parentRefs:
    - name: blagateway
  hostnames:
    - "blagenda.diamondy.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: front
          port: 80
